#!/usr/local/bin/python3
from css_html_js_minify import css_minify
import sass
import glob
import json
import os
import time

def compile(t):
    return sass.compile(string=t)

def minify(t):
    return css_minify(t)


path = 'src/styles'
jayson_name = "styles"

jayson_fn = f"{path}/{jayson_name}.json"

files = [ f for f in glob.glob(f"{path}/*.*css") ]
jayson = {}

for file in files:
    with open(file, "r") as f:
        t=f.read()
        title = file.split('/')[-1].split('.')[0]
        jayson[title] = minify(compile(t))

with open(jayson_fn, "w") as j:
    json.dump(jayson, j)
    
    # time.sleep(1)
print(f":: compiled & minified [{path}] to {jayson_fn} \n :: size -> {round(os.stat(jayson_fn).st_size/1000, 2)} KB")
