#!/bin/bash

ARG1=${2:-yarn}

echo "
welcome to

█░░ █▀▀ █▀▀ ▀▀█▀▀ █▀▀█ █▀▀█ ░░▀ █▀▀ 
█░░ █▀▀ █░░ ░░█░░ █░░█ █▄▄▀ ░░█ ▀▀█ 
▀▀▀ ▀▀▀ ▀▀▀ ░░▀░░ ▀▀▀▀ ▀░▀▀ █▄█ ▀▀▀



Setting up using $ARG1
"

source "./.lector_env/bin/activate"
pip install -r .requirements.txt

$ARG1 install
$ARG1 run dev

export LECTORJSPKG = "$ARG1"

echo "



Goodbye.

We'll meet again.
"
