#!/bin/bash

echo "
welcome to

█░░ █▀▀ █▀▀ ▀▀█▀▀ █▀▀█ █▀▀█ ░░▀ █▀▀ 
█░░ █▀▀ █░░ ░░█░░ █░░█ █▄▄▀ ░░█ ▀▀█ 
▀▀▀ ▀▀▀ ▀▀▀ ░░▀░░ ▀▀▀▀ ▀░▀▀ █▄█ ▀▀▀



Setting up..
"
source "./.lector_env/bin/activate"
pip install -r .requirements.txt
yarn dev

echo "




Goodbye.

We'll meet again.
"
