#!/bin/bash


ARG1=${1:-yarn}

echo "
welcome to

█░░ █▀▀ █▀▀ ▀▀█▀▀ █▀▀█ █▀▀█ ░░▀ █▀▀ 
█░░ █▀▀ █░░ ░░█░░ █░░█ █▄▄▀ ░░█ ▀▀█ 
▀▀▀ ▀▀▀ ▀▀▀ ░░▀░░ ▀▀▀▀ ▀░▀▀ █▄█ ▀▀▀



Setting up using $ARG1
"

source "./.lector_env/bin/activate"
pip install -r .requirements.txt

export LECTORJSPKG="$ARG1"

$ARG1 install
$ARG1 run dev


echo "



Goodbye.

We'll meet again.
"
